language: ruby
sudo: false
cache: bundler
before_script:
  - ./bin/kafka start || true
  - tail -n +1 tmp/*.log
rvm:
  - jruby
  - jruby-head
jdk:
  - openjdk7
script: bundle exec rspec
matrix:
  allow_failure:
    - rvm: jruby-head
