language: ruby
sudo: false
cache: bundler
env:
  - JRUBY_OPTS="$JRUBY_OPTS -Xcli.debug=true --debug"
before_script:
  - ./bin/kafka start
rvm:
  - jruby
  - jruby-head
jdk:
  - openjdk7
script: bundle exec rspec
matrix:
  allow_failure:
    - rvm: jruby-head
after_failure:
  - cat tmp/*.log
