language: ruby
sudo: false
cache: bundler
env:
  - JRUBY_OPTS="$JRUBY_OPTS -Xcli.debug=true --debug"
before_script:
  - ./bin/kafka start
rvm:
  - jruby-1.7
  - jruby-9.0.0.0
jdk:
  - openjdk7
script: bundle exec rspec
after_failure:
  - cat tmp/*.log
